name: Build and deploy to Server

on:
  pull_request:
    branches:
      - dev
  push:
    branches:
      - feat/setup-CI-CD
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Copy Repository
        uses: actions/checkout@v4

      - name: Running Docker Compose
        run: docker compose up -d --build